$PRJ_PATH/rtl/A7LITE_TEST.v
$PRJ_PATH/rtl/AxiMemRdCtrl.v
$PRJ_PATH/rtl/RstSync.v
$PRJ_PATH/rtl/TMDSCtrlTop.v
$PRJ_PATH/rtl/TMDSEncoder.v
$PRJ_PATH/rtl/TMDSOutputSerdes.v
$PRJ_PATH/rtl/VGACtrlTop.v
$PRJ_PATH/rtl/async_fifo.v
$PRJ_PATH/rtl/axi_ram.v
$PRJ_PATH/rtl/uriscv_core/uriscv_defs.sv
$PRJ_PATH/rtl/uriscv_core/uriscv_alu.sv
$PRJ_PATH/rtl/uriscv_core/uriscv_lsu.sv
$PRJ_PATH/rtl/uriscv_core/uriscv_csr.sv
$PRJ_PATH/rtl/uriscv_core/uriscv_muldiv.sv
$PRJ_PATH/rtl/uriscv_core/uriscv_branch.sv
$PRJ_PATH/rtl/uriscv_core/uriscv_core.sv
$PRJ_PATH/rtl/uriscv_core/uriscv_tcm.sv
$PRJ_PATH/rtl/uriscv_core/uriscv_top.sv
$PRJ_PATH/rtl/uriscv_core/uriscv_ahb_top.sv
$PRJ_PATH/rtl/uriscv_core/uriscv_axi_top.sv
$PRJ_PATH/rtl/axi_infrastructure/arbiter.v
$PRJ_PATH/rtl/axi_infrastructure/priority_encoder.v
$PRJ_PATH/rtl/axi_infrastructure/axi_register_rd.v
$PRJ_PATH/rtl/axi_infrastructure/axi_register_wr.v
$PRJ_PATH/rtl/axi_infrastructure/axi_crossbar_addr.v
$PRJ_PATH/rtl/axi_infrastructure/axi_crossbar_rd.v
$PRJ_PATH/rtl/axi_infrastructure/axi_crossbar_wr.v
$PRJ_PATH/rtl/axi_infrastructure/axi_crossbar.v

